# Generated by Django 5.1.4 on 2026-05-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='flag',
            field=models.CharField(default='🌍', max_length=10),
        ),
    ]
